name: Run job

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'samsmithnz/RepoAutomationUnitTests'
        token: ${{ secrets.PAT_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Get outdated packages
      shell: pwsh
      run: |
        cd src 
        $result = dotnet list package --outdated --format json
        write-host "Results!"
        write-host $result
        if ($result.length -gt 40000)
        {
          write-host "Result is too large to be assigned to an environment variable."
        }
