name: Run job

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  processRepos:
    name: Process repos
    env:
      user: samsmithnz
    strategy:
      matrix:
        repo: ['samsmithnz/RepoAutomationUnitTests', 'samsmithnz/RepoAutomation', 'samsmithnz/RepoGovernance']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ matrix.repo }}
        token: ${{ secrets.PAT_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Scan and update outdated NuGet packages
      shell: pwsh
      run: |
        cd src 
        $resultDeprecated = dotnet list package --deprecated --format json
        if ($resultDeprecated.length -gt 40000)
        {
          write-host "Deprcated result is too large to be assigned to an environment variable."
        }
        $resultOutDated = dotnet list package --outdated --format json
        if ($resultOutDated.length -gt 40000)
        {
          write-host "Outdated result is too large to be assigned to an environment variable."
        }
        $resultVulnerable = dotnet list package --vulnerable --format json
        if ($resultVulnerable.length -gt 40000)
        {
          write-host "Vulnerable result is too large to be assigned to an environment variable."
        }
        $user = "${{ env.user }}"
        $owner = "${{ matrix.repo }}".split('/')[0]
        $repo = "${{ matrix.repo }}".split('/')[1]
        #Deprecated packages
        $NuGetDeprecatedPayload = @{
          User = $user
          Owner = $owner
          Repo = $repo
          JsonPayload = $resultDeprecated
          PayloadType = "Deprecated"
        } | ConvertTo-Json -Depth 5
        Invoke-WebRequest -Uri https://repogovernance-prod-eu-service.azurewebsites.net/api/SummaryItems/UpdateSummaryItemNuGetPackageStats -ContentType "application/json" -Method POST -Body $NuGetDeprecatedPayload
        #Outdated packages
        $NuGetOutdatedPayload = @{
          User = $user
          Owner = $owner
          Repo = $repo
          JsonPayload = $resultOutDated
          PayloadType = "Outdated"
        } | ConvertTo-Json -Depth 5
        Invoke-WebRequest -Uri https://repogovernance-prod-eu-service.azurewebsites.net/api/SummaryItems/UpdateSummaryItemNuGetPackageStats -ContentType "application/json" -Method POST -Body $NuGetOutdatedPayload
        #Vulnerable packages        
        $NuGetVulnerablePayload = @{
          User = $user
          Owner = $owner
          Repo = $repo
          JsonPayload = $resultVulnerable
          PayloadType = "Vulnerable"
        } | ConvertTo-Json -Depth 5
        Invoke-WebRequest -Uri https://repogovernance-prod-eu-service.azurewebsites.net/api/SummaryItems/UpdateSummaryItemNuGetPackageStats -ContentType "application/json" -Method POST -Body $NuGetVulnerablePayload
        
